global:
 message: Welcome to global Microservices Environment!!
 logging:
   level:
    root: INFO
     eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
 management: 
    endpoints:
     web:
       exposure:
        include: health, info, refresh
    endpoint:
       health:
        show-details: always



