spring:
 application:
   name: customer-service
 datasource:
   url: mysql://localhost:3306/customer_master
    driverClassName: com.mysql.jdbc.Driver
jpa:
hibernate:
  ddl-auto: none
show-sql: false
